apiVersion: v1
kind: ConfigMap
metadata:
  name: case-study-config
  namespace: case-study
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  COUNTRY_INFO_SOAP_BASE_URL: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"

